# 配置端口号
server:
  port: 6000

# 配置服务名
spring:
  application:
    name: atguigu-crowd-order

# 配置Thymeleaf视图解析器
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# 配置session共享功能
  redis:
    host: 192.168.0.19
  session:
    store-type: redis

# 配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

# 配置Hystrix负载均衡时间
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000

