server:
  port: 5000

spring:
  application:
    name: atguigu-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #  做Session共享（用到Redis）
  redis:
    host: 192.168.0.19
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

aliyun:
  oss:
    access-key-id: XXX
    access-key-secret: XXX
    bucket-domain: http://XXX
    bucket-name: mystudyatguigu
    end-point: http://XXX

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
