package com.atguigu.crowd.mapper;

import com.atguigu.crowd.entity.po.MemberConfirmInfoPO;
import com.atguigu.crowd.entity.po.MemberConfirmInfoPOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface MemberConfirmInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int countByExample(MemberConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int deleteByExample(MemberConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int insert(MemberConfirmInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int insertSelective(MemberConfirmInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    List<MemberConfirmInfoPO> selectByExample(MemberConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    MemberConfirmInfoPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") MemberConfirmInfoPO record, @Param("example") MemberConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByExample(@Param("record") MemberConfirmInfoPO record, @Param("example") MemberConfirmInfoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByPrimaryKeySelective(MemberConfirmInfoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_confirm_info
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByPrimaryKey(MemberConfirmInfoPO record);
}