package com.atguigu.crowd.mapper;

import com.atguigu.crowd.entity.po.OrderPO;
import com.atguigu.crowd.entity.po.OrderPOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface OrderPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int countByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int deleteByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int insert(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int insertSelective(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    List<OrderPO> selectByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    OrderPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderPO record, @Param("example") OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByExample(@Param("record") OrderPO record, @Param("example") OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByPrimaryKeySelective(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByPrimaryKey(OrderPO record);
}