package com.atguigu.crowd.mapper;


import com.atguigu.crowd.entity.po.OrderProjectPO;
import com.atguigu.crowd.entity.po.OrderProjectPOExample;
import com.atguigu.crowd.entity.vo.OrderProjectVO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface OrderProjectPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int countByExample(OrderProjectPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int deleteByExample(OrderProjectPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int insert(OrderProjectPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int insertSelective(OrderProjectPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    List<OrderProjectPO> selectByExample(OrderProjectPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    OrderProjectPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderProjectPO record, @Param("example") OrderProjectPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByExample(@Param("record") OrderProjectPO record, @Param("example") OrderProjectPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByPrimaryKeySelective(OrderProjectPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_project
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    int updateByPrimaryKey(OrderProjectPO record);

    OrderProjectVO selectOrderProjectVO(Integer returnId);

}