package com.atguigu.crowd.mapper;

import com.atguigu.crowd.entity.po.ReturnPO;
import com.atguigu.crowd.entity.po.ReturnPOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ReturnPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int countByExample(ReturnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int deleteByExample(ReturnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int insert(ReturnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int insertSelective(ReturnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    List<ReturnPO> selectByExample(ReturnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    ReturnPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") ReturnPO record, @Param("example") ReturnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByExample(@Param("record") ReturnPO record, @Param("example") ReturnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByPrimaryKeySelective(ReturnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByPrimaryKey(ReturnPO record);

    void insertReturnPOBatch(@Param("returnPOList") List<ReturnPO> returnPOList, @Param("projectId") Integer projectId);
}