package com.atguigu.crowd.mapper;


import com.atguigu.crowd.entity.po.TypePO;
import com.atguigu.crowd.entity.po.TypePOExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TypePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int countByExample(TypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int deleteByExample(TypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int insert(TypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int insertSelective(TypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    List<TypePO> selectByExample(TypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    TypePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") TypePO record, @Param("example") TypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByExample(@Param("record") TypePO record, @Param("example") TypePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByPrimaryKeySelective(TypePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    int updateByPrimaryKey(TypePO record);
}