package com.atguigu.crowd.entity.po;

public class AddressPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.receive_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String receiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.phone_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.member_id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.id
     *
     * @return the value of t_address.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.id
     *
     * @param id the value for t_address.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.receive_name
     *
     * @return the value of t_address.receive_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.receive_name
     *
     * @param receiveName the value for t_address.receive_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName == null ? null : receiveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.phone_num
     *
     * @return the value of t_address.phone_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.phone_num
     *
     * @param phoneNum the value for t_address.phone_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address
     *
     * @return the value of t_address.address
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address
     *
     * @param address the value for t_address.address
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.member_id
     *
     * @return the value of t_address.member_id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.member_id
     *
     * @param memberId the value for t_address.member_id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}