package com.atguigu.crowd.entity.po;

public class MemberLaunchInfoPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_launch_info.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_launch_info.memberid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_launch_info.description_simple
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String descriptionSimple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_launch_info.description_detail
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String descriptionDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_launch_info.phone_num
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_launch_info.service_num
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String serviceNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_launch_info.id
     *
     * @return the value of t_member_launch_info.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_launch_info.id
     *
     * @param id the value for t_member_launch_info.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_launch_info.memberid
     *
     * @return the value of t_member_launch_info.memberid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_launch_info.memberid
     *
     * @param memberid the value for t_member_launch_info.memberid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_launch_info.description_simple
     *
     * @return the value of t_member_launch_info.description_simple
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getDescriptionSimple() {
        return descriptionSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_launch_info.description_simple
     *
     * @param descriptionSimple the value for t_member_launch_info.description_simple
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setDescriptionSimple(String descriptionSimple) {
        this.descriptionSimple = descriptionSimple == null ? null : descriptionSimple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_launch_info.description_detail
     *
     * @return the value of t_member_launch_info.description_detail
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getDescriptionDetail() {
        return descriptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_launch_info.description_detail
     *
     * @param descriptionDetail the value for t_member_launch_info.description_detail
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setDescriptionDetail(String descriptionDetail) {
        this.descriptionDetail = descriptionDetail == null ? null : descriptionDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_launch_info.phone_num
     *
     * @return the value of t_member_launch_info.phone_num
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_launch_info.phone_num
     *
     * @param phoneNum the value for t_member_launch_info.phone_num
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_launch_info.service_num
     *
     * @return the value of t_member_launch_info.service_num
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getServiceNum() {
        return serviceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_launch_info.service_num
     *
     * @param serviceNum the value for t_member_launch_info.service_num
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setServiceNum(String serviceNum) {
        this.serviceNum = serviceNum == null ? null : serviceNum.trim();
    }
}