package com.atguigu.crowd.entity.po;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@NoArgsConstructor
@AllArgsConstructor
@ToString
@Data
public class MemberPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.id
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.loginacct
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private String loginacct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.userpswd
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private String userpswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.username
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.email
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.authstatus
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private Integer authstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.usertype
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.realname
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.cardnum
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private String cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.accttype
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    private Integer accttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.id
     *
     * @return the value of t_member.id
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.id
     *
     * @param id the value for t_member.id
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.loginacct
     *
     * @return the value of t_member.loginacct
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public String getLoginacct() {
        return loginacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.loginacct
     *
     * @param loginacct the value for t_member.loginacct
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setLoginacct(String loginacct) {
        this.loginacct = loginacct == null ? null : loginacct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.userpswd
     *
     * @return the value of t_member.userpswd
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public String getUserpswd() {
        return userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.userpswd
     *
     * @param userpswd the value for t_member.userpswd
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setUserpswd(String userpswd) {
        this.userpswd = userpswd == null ? null : userpswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.username
     *
     * @return the value of t_member.username
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.username
     *
     * @param username the value for t_member.username
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.email
     *
     * @return the value of t_member.email
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.email
     *
     * @param email the value for t_member.email
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.authstatus
     *
     * @return the value of t_member.authstatus
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public Integer getAuthstatus() {
        return authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.authstatus
     *
     * @param authstatus the value for t_member.authstatus
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setAuthstatus(Integer authstatus) {
        this.authstatus = authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.usertype
     *
     * @return the value of t_member.usertype
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.usertype
     *
     * @param usertype the value for t_member.usertype
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.realname
     *
     * @return the value of t_member.realname
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.realname
     *
     * @param realname the value for t_member.realname
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.cardnum
     *
     * @return the value of t_member.cardnum
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.cardnum
     *
     * @param cardnum the value for t_member.cardnum
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum == null ? null : cardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.accttype
     *
     * @return the value of t_member.accttype
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public Integer getAccttype() {
        return accttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.accttype
     *
     * @param accttype the value for t_member.accttype
     *
     * @mbggenerated Mon Nov 29 16:36:03 CST 2021
     */
    public void setAccttype(Integer accttype) {
        this.accttype = accttype;
    }
}