package com.atguigu.crowd.entity.po;

public class OrderProjectPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.project_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.launch_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String launchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.return_content
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String returnContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.return_count
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer returnCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.support_price
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer supportPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.freight
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_project.order_id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.id
     *
     * @return the value of t_order_project.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.id
     *
     * @param id the value for t_order_project.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.project_name
     *
     * @return the value of t_order_project.project_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.project_name
     *
     * @param projectName the value for t_order_project.project_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.launch_name
     *
     * @return the value of t_order_project.launch_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getLaunchName() {
        return launchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.launch_name
     *
     * @param launchName the value for t_order_project.launch_name
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setLaunchName(String launchName) {
        this.launchName = launchName == null ? null : launchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.return_content
     *
     * @return the value of t_order_project.return_content
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getReturnContent() {
        return returnContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.return_content
     *
     * @param returnContent the value for t_order_project.return_content
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setReturnContent(String returnContent) {
        this.returnContent = returnContent == null ? null : returnContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.return_count
     *
     * @return the value of t_order_project.return_count
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getReturnCount() {
        return returnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.return_count
     *
     * @param returnCount the value for t_order_project.return_count
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setReturnCount(Integer returnCount) {
        this.returnCount = returnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.support_price
     *
     * @return the value of t_order_project.support_price
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getSupportPrice() {
        return supportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.support_price
     *
     * @param supportPrice the value for t_order_project.support_price
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setSupportPrice(Integer supportPrice) {
        this.supportPrice = supportPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.freight
     *
     * @return the value of t_order_project.freight
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.freight
     *
     * @param freight the value for t_order_project.freight
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_project.order_id
     *
     * @return the value of t_order_project.order_id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_project.order_id
     *
     * @param orderId the value for t_order_project.order_id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}