package com.atguigu.crowd.entity.po;

public class OrderPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_order_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String payOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_amount
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.invoice
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private Integer invoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.invoice_title
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_remark
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    private String orderRemark;

    private Integer addressId;

    public Integer getAddressId() {
        return addressId;
    }

    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_num
     *
     * @return the value of t_order.order_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_num
     *
     * @param orderNum the value for t_order.order_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_order_num
     *
     * @return the value of t_order.pay_order_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getPayOrderNum() {
        return payOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_order_num
     *
     * @param payOrderNum the value for t_order.pay_order_num
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setPayOrderNum(String payOrderNum) {
        this.payOrderNum = payOrderNum == null ? null : payOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_amount
     *
     * @return the value of t_order.order_amount
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_amount
     *
     * @param orderAmount the value for t_order.order_amount
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.invoice
     *
     * @return the value of t_order.invoice
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public Integer getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.invoice
     *
     * @param invoice the value for t_order.invoice
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setInvoice(Integer invoice) {
        this.invoice = invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.invoice_title
     *
     * @return the value of t_order.invoice_title
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.invoice_title
     *
     * @param invoiceTitle the value for t_order.invoice_title
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_remark
     *
     * @return the value of t_order.order_remark
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_remark
     *
     * @param orderRemark the value for t_order.order_remark
     *
     * @mbggenerated Thu Dec 09 17:11:25 CST 2021
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }
}