package com.atguigu.crowd.entity.po;

public class ProjectPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.project_name
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.project_description
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String projectDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.money
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.day
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.status
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.deploydate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String deploydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.supportmoney
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Long supportmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.supporter
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer supporter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.completion
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer completion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.memberid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.createdate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.follower
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer follower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project.header_picture_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String headerPicturePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.id
     *
     * @return the value of t_project.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.id
     *
     * @param id the value for t_project.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.project_name
     *
     * @return the value of t_project.project_name
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.project_name
     *
     * @param projectName the value for t_project.project_name
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.project_description
     *
     * @return the value of t_project.project_description
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.project_description
     *
     * @param projectDescription the value for t_project.project_description
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription == null ? null : projectDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.money
     *
     * @return the value of t_project.money
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.money
     *
     * @param money the value for t_project.money
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.day
     *
     * @return the value of t_project.day
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.day
     *
     * @param day the value for t_project.day
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.status
     *
     * @return the value of t_project.status
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.status
     *
     * @param status the value for t_project.status
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.deploydate
     *
     * @return the value of t_project.deploydate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getDeploydate() {
        return deploydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.deploydate
     *
     * @param deploydate the value for t_project.deploydate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setDeploydate(String deploydate) {
        this.deploydate = deploydate == null ? null : deploydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.supportmoney
     *
     * @return the value of t_project.supportmoney
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Long getSupportmoney() {
        return supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.supportmoney
     *
     * @param supportmoney the value for t_project.supportmoney
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setSupportmoney(Long supportmoney) {
        this.supportmoney = supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.supporter
     *
     * @return the value of t_project.supporter
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getSupporter() {
        return supporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.supporter
     *
     * @param supporter the value for t_project.supporter
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setSupporter(Integer supporter) {
        this.supporter = supporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.completion
     *
     * @return the value of t_project.completion
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getCompletion() {
        return completion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.completion
     *
     * @param completion the value for t_project.completion
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setCompletion(Integer completion) {
        this.completion = completion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.memberid
     *
     * @return the value of t_project.memberid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.memberid
     *
     * @param memberid the value for t_project.memberid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.createdate
     *
     * @return the value of t_project.createdate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.createdate
     *
     * @param createdate the value for t_project.createdate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.follower
     *
     * @return the value of t_project.follower
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getFollower() {
        return follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.follower
     *
     * @param follower the value for t_project.follower
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setFollower(Integer follower) {
        this.follower = follower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project.header_picture_path
     *
     * @return the value of t_project.header_picture_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getHeaderPicturePath() {
        return headerPicturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project.header_picture_path
     *
     * @param headerPicturePath the value for t_project.header_picture_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setHeaderPicturePath(String headerPicturePath) {
        this.headerPicturePath = headerPicturePath == null ? null : headerPicturePath.trim();
    }
}