package com.atguigu.crowd.entity.po;

public class ProjectItemPicPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_item_pic.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_item_pic.projectid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_item_pic.item_pic_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String itemPicPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_item_pic.id
     *
     * @return the value of t_project_item_pic.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_item_pic.id
     *
     * @param id the value for t_project_item_pic.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_item_pic.projectid
     *
     * @return the value of t_project_item_pic.projectid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_item_pic.projectid
     *
     * @param projectid the value for t_project_item_pic.projectid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_item_pic.item_pic_path
     *
     * @return the value of t_project_item_pic.item_pic_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getItemPicPath() {
        return itemPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_item_pic.item_pic_path
     *
     * @param itemPicPath the value for t_project_item_pic.item_pic_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setItemPicPath(String itemPicPath) {
        this.itemPicPath = itemPicPath == null ? null : itemPicPath.trim();
    }
}