package com.atguigu.crowd.entity.po;

public class ReturnPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.projectid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.supportmoney
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer supportmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.content
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.count
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.signalpurchase
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer signalpurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.purchase
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer purchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.freight
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.invoice
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer invoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.returndate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private Integer returndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_return.describ_pic_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    private String describPicPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.id
     *
     * @return the value of t_return.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.id
     *
     * @param id the value for t_return.id
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.projectid
     *
     * @return the value of t_return.projectid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.projectid
     *
     * @param projectid the value for t_return.projectid
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.type
     *
     * @return the value of t_return.type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.type
     *
     * @param type the value for t_return.type
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.supportmoney
     *
     * @return the value of t_return.supportmoney
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getSupportmoney() {
        return supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.supportmoney
     *
     * @param supportmoney the value for t_return.supportmoney
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setSupportmoney(Integer supportmoney) {
        this.supportmoney = supportmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.content
     *
     * @return the value of t_return.content
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.content
     *
     * @param content the value for t_return.content
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.count
     *
     * @return the value of t_return.count
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.count
     *
     * @param count the value for t_return.count
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.signalpurchase
     *
     * @return the value of t_return.signalpurchase
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getSignalpurchase() {
        return signalpurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.signalpurchase
     *
     * @param signalpurchase the value for t_return.signalpurchase
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setSignalpurchase(Integer signalpurchase) {
        this.signalpurchase = signalpurchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.purchase
     *
     * @return the value of t_return.purchase
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getPurchase() {
        return purchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.purchase
     *
     * @param purchase the value for t_return.purchase
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setPurchase(Integer purchase) {
        this.purchase = purchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.freight
     *
     * @return the value of t_return.freight
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.freight
     *
     * @param freight the value for t_return.freight
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.invoice
     *
     * @return the value of t_return.invoice
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.invoice
     *
     * @param invoice the value for t_return.invoice
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setInvoice(Integer invoice) {
        this.invoice = invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.returndate
     *
     * @return the value of t_return.returndate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public Integer getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.returndate
     *
     * @param returndate the value for t_return.returndate
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setReturndate(Integer returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_return.describ_pic_path
     *
     * @return the value of t_return.describ_pic_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public String getDescribPicPath() {
        return describPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_return.describ_pic_path
     *
     * @param describPicPath the value for t_return.describ_pic_path
     *
     * @mbggenerated Tue Dec 07 10:50:39 CST 2021
     */
    public void setDescribPicPath(String describPicPath) {
        this.describPicPath = describPicPath == null ? null : describPicPath.trim();
    }
}